travis:
  secure:
    BINSTAR_TOKEN: llGk2UJdf42T4EEK1gGRXxlZveWBn80kPfIDM5LepEzQl55/XPXd/TTxynypiydKjTMsPy8+h6bS37Ee/3Vssh68EEQ5qxL0p8PQdXk+MQfO4C31Pw1jd3Gc5e1C9xnv+fMXuOCY2G5jl2ID1HvfNU0p/95Gj109PoFTdVjX0z1QXIhUoR5Ns75knd/lmFEdhRKKnjLmy8QGFtE8yOGOXE1U7eVq5vyFhCUREC4MGJgb/AXeC5GW83/HxEMVvtKyXiXsRLQ9XLPErK31Iw2i427RUUE2YtEK1OeiIpwv1aMthPvF+16nhx+ogtPmp7URDeynOmEdkQ5X54rYhlVG5Qqm6v+DQru3TVa/2YlMNzQHV78dVnLb2cU4kMEhkB0pTT2tT4m120snEQDI39bI5B89pcqo8C83i77WiL1jKMnK6mVdFnCCu7ohh7cOfJ1S/GlKlYZSkqRoUTMObxcct/YBuB2DAnU7btLO0XtZI4kbLO1IsuM2aCwfEjSWp/eQOtb0DHKDhdW/LBrafbJcS9AarZyjUS7/7G3U1gmBjEZ9r/iZF20LABa89kNrQOQPBx3pMfm6zFty89ABVY/fvdg/69qGzAUgkqnUa5x4EOU7vteEMMWO7H+wN9eZo6H4dScBsjx4m+lga+sFMRKOljV24QQZFGerQlE1lO978H8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
